    language: python
    python:
        - "2.7"
        - "pypy"
    env:
        - TORNADO=3.2
        - TORNADO=4.0
        - TORNADO=4.0.2
    install:
        - pip install -q tornado==$TORNADO
        - pip install pep8
        - pip install https://github.com/dcramer/pyflakes/tarball/master
        - pip install -r requirements.txt
        - pip install -q -e .
    before_script:
        - "pep8 --exclude=migrations --ignore=E501,E225 src"
        - pyflakes -x W src
    script:
        - python setup.py test
